### ISSUE TITLE
i3 has often overloads my CPU up to 100%

### ISSUE THREAD

**Issue by Goodmind** [i3/i3#1862]
Hello,

```i3``` has often overloads my CPU up to 100%.

My CPU is ```Intel(R) Core(TM)2 Quad CPU Q8300```.

http://logs.i3wm.org/logs/5177924793663488.bz2
```/var/run/user/1000/i3/errorlog.412``` contents:
```
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: Received ExposeEvent for unknown window 0x01000000
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: Received ConfigureNotify for unknown window 0x01000003
ERROR: Received ConfigureNotify for unknown window 0x01000003
ERROR: Received ConfigureNotify for unknown window 0x01000006
ERROR: Received ConfigureNotify for unknown window 0x01000006
ERROR: Received ConfigureNotify for unknown window 0x01000009
ERROR: Received ConfigureNotify for unknown window 0x01000009
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: Received ExposeEvent for unknown window 0x01000000
ERROR: Received ConfigureNotify for unknown window 0x01000000
ERROR: No output found at destination coordinates, centering floating window on current ws
```

My ```i3``` version is:
```
Binary i3 version:  4.10.3 (2015-07-30, branch "4.10.3") © 2009-2014 Michael Stapelberg and contributors
Running i3 version: 4.10.3 (2015-07-30, branch "4.10.3") (pid 30076)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3-with-/i3

```

I realized that it is ```mpd``` which depends on ```ffmpeg``` which depends on ```sdl```
Reference: https://github.com/Airblader/i3/issues/56

**Comment by Airblader** [comment]
Please try to read more carefully what I say – you should've installed the normal i3 first, then *reproduce* the problem there and *then* report it.

Michael may very well reject this report based on the fact that you are running i3-gaps instead of i3, even if I don't think that it makes a difference.

**Comment by Goodmind** [comment]
Oh, okay I'll reopen it if it reproduced

**Comment by Goodmind** [comment]
Hello,

I can reproduce this with normal i3

http://logs.i3wm.org/logs/5177924793663488.bz2

**Comment by Goodmind** [comment]
Is there any workaround or will I wait for new minor version or patch?

**Comment by Airblader** [comment]
Until we find the reason and it is fixed, even a new version won't help. I'm pretty sure this won't even turn out to be an i3 problem, but you never know.

**Comment by stapelberg** [comment]
The log covers about half an hour, which is far too long to read it.

Can you list clear steps to reproduce this issue please?

**Comment by Goodmind** [comment]
Just run ```mpd``` from user and add some music to it
https://wiki.archlinux.org/index.php/Music_Player_Daemon

after a hour of ```mpd``` ```i3``` is overload my CPU up to 100%

**Comment by stapelberg** [comment]
mpd is a daemon that doesn’t communicate with X11 at all, so I don’t see how it could influence i3 at all…?

**Comment by Goodmind** [comment]
But, without it runned all works fine

**Comment by stapelberg** [comment]
What’s the result of `tr '\0' '\n' < /proc/$(pidof mpd)/environ`?

**Comment by Goodmind** [comment]
```
XDG_SESSION_ID=c2
GDM_LANG=ru_RU.utf8
GTK_MODULES=canberra-gtk-module
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
HOME=/home/goodmind
DISPLAY=:0.0
XDG_SESSION_DESKTOP=i3-with-shmlog
XDG_SEAT=seat0
_=/usr/bin/mpd
GDMSESSION=i3-with-shmlog
WINDOWID=29368358
LOGNAME=goodmind
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-St0wFsmzUB,guid=7e1cdd346129db327505780555dc86f2
XDG_RUNTIME_DIR=/run/user/1000
LANG=ru_RU.utf8
XDG_SEAT_PATH=/org/freedesktop/DisplayManager/Seat0
XDG_SESSION_TYPE=x11
MAIL=/var/spool/mail/goodmind
TERM=xterm
COLORTERM=xfce4-terminal
SHLVL=2
XDG_VTNR=7
XAUTHORITY=/home/goodmind/.Xauthority
XDG_SESSION_PATH=/org/freedesktop/DisplayManager/Session0
DESKTOP_SESSION=i3-with-shmlog
XDG_GREETER_DATA_DIR=/var/lib/lightdm-data/goodmind
PWD=/home/goodmind
USER=goodmind
SHELL=/usr/bin/zsh
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
OLDPWD=/home/goodmind
```

**Comment by stapelberg** [comment]
Can you run mpd with an empty DISPLAY= variable just to make sure it’s not mpd which interferes with i3?

**Comment by Goodmind** [comment]
Your solution is not run ```mpd``` from i3 config?

```
HOME=/home/goodmind
USER=goodmind
SHELL=/usr/bin/zsh
TERM=linux
PATH=/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
MAIL=/var/spool/mail/goodmind
LOGNAME=goodmind
XDG_SESSION_ID=c3
XDG_RUNTIME_DIR=/run/user/1000
XDG_SEAT=seat0
XDG_VTNR=1
SHLVL=1
PWD=/home/goodmind
OLDPWD=/home/goodmind
LANG=ru_RU.UTF-8
MOZ_PLUGIN_PATH=/usr/lib/mozilla/plugins
_=/usr/bin/mpd
```

**Comment by Goodmind** [comment]
I have 100% CPU again with mpd runned from tty

**Comment by stapelberg** [comment]
During a period where you have 100% cpu, what’s the output of `ps aufxww` and can you provide like 5 second’s worth of `i3-dump-log` output?

**Comment by Goodmind** [comment]
Oh, sorry, I already kill i3

**Comment by Goodmind** [comment]
```ps aufxww``` output while 100% cpu:
```
SER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root         2  0.0  0.0      0     0 ?        S    20:12   0:00 [kthreadd]
root         3  0.6  0.0      0     0 ?        S    20:12   1:11  \_ [ksoftirqd/0]
root         5  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/0:0H]
root         6  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [kworker/u8:0]
root         7  0.3  0.0      0     0 ?        S    20:12   0:37  \_ [rcu_preempt]
root         8  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [rcu_sched]
root         9  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [rcu_bh]
root        10  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [migration/0]
root        11  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [watchdog/0]
root        12  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [watchdog/1]
root        13  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [migration/1]
root        14  0.6  0.0      0     0 ?        S    20:12   1:17  \_ [ksoftirqd/1]
root        16  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/1:0H]
root        17  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [watchdog/2]
root        18  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [migration/2]
root        19  0.5  0.0      0     0 ?        S    20:12   1:05  \_ [ksoftirqd/2]
root        21  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/2:0H]
root        22  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [watchdog/3]
root        23  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [migration/3]
root        24  0.6  0.0      0     0 ?        S    20:12   1:14  \_ [ksoftirqd/3]
root        26  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/3:0H]
root        27  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [khelper]
root        28  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [kdevtmpfs]
root        29  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [netns]
root        30  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [perf]
root        31  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [khungtaskd]
root        32  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [writeback]
root        33  0.0  0.0      0     0 ?        SN   20:12   0:00  \_ [ksmd]
root        34  0.0  0.0      0     0 ?        SN   20:12   0:02  \_ [khugepaged]
root        35  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [crypto]
root        36  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kintegrityd]
root        37  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [bioset]
root        38  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kblockd]
root        39  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [devfreq_wq]
root        44  0.0  0.0      0     0 ?        S    20:12   0:01  \_ [kswapd0]
root        45  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [fsnotify_mark]
root        51  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kthrotld]
root        55  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [ipv6_addrconf]
root        56  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [deferwq]
root       106  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [firewire]
root       107  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [ata_sff]
root       108  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [firewire_ohci]
root       109  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [scsi_eh_0]
root       110  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [scsi_tmf_0]
root       111  0.0  0.0      0     0 ?        S    20:12   0:00  \_ [scsi_eh_1]
root       112  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [scsi_tmf_1]
root       120  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/3:1H]
root       121  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/1:1H]
root       122  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/0:1H]
root       123  0.0  0.0      0     0 ?        S<   20:12   0:00  \_ [kworker/2:1H]
root       143  0.0  0.0      0     0 ?        S    20:14   0:01  \_ [jbd2/sda5-8]
root       144  0.0  0.0      0     0 ?        S<   20:14   0:00  \_ [ext4-rsv-conver]
root       181  0.0  0.0      0     0 ?        S    20:14   0:04  \_ [kworker/0:2]
root       241  0.0  0.0      0     0 ?        S<   20:14   0:00  \_ [kvm-irqfd-clean]
root       250  0.0  0.0      0     0 ?        S<   20:15   0:00  \_ [kfd_process_wq]
root       251  0.0  0.0      0     0 ?        S<   20:15   0:00  \_ [ttm_swap]
root       258  0.0  0.0      0     0 ?        S<   20:15   0:00  \_ [radeon-crtc]
root       259  0.0  0.0      0     0 ?        S<   20:15   0:00  \_ [radeon-crtc]
root       289  0.0  0.0      0     0 ?        S<   20:15   0:00  \_ [cfg80211]
root      2486  0.0  0.0      0     0 ?        S    20:34   0:06  \_ [kworker/2:0]
root     25491  0.0  0.0      0     0 ?        S    21:35   0:00  \_ [kworker/0:1]
root      6951  0.0  0.0      0     0 ?        S    21:58   0:03  \_ [kworker/3:1]
root      7999  0.0  0.0      0     0 ?        S    21:59   0:01  \_ [kworker/1:2]
root       529  0.0  0.0      0     0 ?        S    22:11   0:00  \_ [kworker/u8:2]
root      5076  0.0  0.0      0     0 ?        S    22:30   0:00  \_ [kworker/3:2]
root      5078  0.0  0.0      0     0 ?        S    22:30   0:02  \_ [kworker/1:0]
root     29869  0.0  0.0      0     0 ?        S    23:15   0:00  \_ [kworker/2:2]
root      7395  0.0  0.0      0     0 ?        S    23:20   0:00  \_ [kworker/2:1]
root         1  0.0  0.2 181804  4252 ?        Ss   20:12   0:00 /sbin/init
root       173  0.0  0.9  70996 18836 ?        Ss   20:14   0:00 /usr/lib/systemd/systemd-journald
root       202  0.0  0.1  35796  2344 ?        Ss   20:14   0:00 /usr/lib/systemd/systemd-udevd
root       272  0.0  0.1  15388  2504 ?        Ss   20:15   0:00 /usr/lib/systemd/systemd-logind
dbus       273  0.0  0.1  35204  3380 ?        Ss   20:15   0:00 /usr/bin/dbus-daemon --system --address=systemd: --nofork --nopidfile --systemd-activation
root       274  0.0  0.1  18104  2828 ?        Ss   20:15   0:08 /sbin/mount.ntfs /dev/sda2 /mnt/windows -o rw
root       295  0.0  0.3 267984  6804 ?        SLsl 20:15   0:00 /usr/bin/lightdm
root      5081  6.2  3.1 261820 65068 tty7     Ssl+ 22:30   3:16  \_ /usr/lib/xorg-server/Xorg :0 -seat seat0 -auth /run/lightdm/root/:0 -nolisten tcp vt7 -novtswitch
root      5116  0.0  0.4 259908  9516 ?        Sl   22:30   0:00  \_ lightdm --session-child 13 20
goodmind  5121  2.8  1.5 171340 32400 ?        Rs   22:30   1:30      \_ i3-with-shmlog -a --restart /run/user/1000/i3/restart-state.5121
root       296  0.0  0.2  89848  4272 ?        Ss   20:15   0:00 login -- goodmind
goodmind 17214  0.0  0.2  38924  5592 tty1     Ss   22:20   0:01  \_ -zsh
goodmind 11682  0.0  0.1  38784  3524 tty1     R+   23:22   0:00      \_ ps aufxww
root       404  0.0  0.0   4504  1320 ?        Ss   20:15   0:00 /usr/bin/dhcpcd -q -w enp3s0
ntp        406  0.0  0.7 105656 15600 ?        SLs  20:15   0:00 /usr/bin/ntpd -g -u ntp:ntp
goodmind   421  0.0  0.1  35860  3528 ?        Ss   20:17   0:00 /usr/lib/systemd/systemd --user
goodmind   422  0.0  0.0  96676   220 ?        S    20:17   0:00  \_ (sd-pam)
root       467  0.0  0.0  30976  1560 ?        Ss   20:17   0:00 /usr/bin/wpa_supplicant -u
polkitd    485  0.0  0.7 523184 15016 ?        Ssl  20:17   0:00 /usr/lib/polkit-1/polkitd --no-debug
root       508  0.0  0.2 228272  6156 ?        Ssl  20:17   0:00 /usr/lib/upower/upowerd
rtkit      553  0.0  0.1 181748  3028 ?        SNsl 20:17   0:00 /usr/lib/rtkit/rtkit-daemon
root      2471  0.0  0.4 365356  8552 ?        Ssl  20:34   0:01 /usr/lib/udisks2/udisksd --no-debug
root     10492  0.0  0.3 190840  6700 ?        Ss   21:27   0:01 /opt/logmein-hamachi/bin/hamachid
goodmind 31610  0.3  0.7 579172 15220 ?        Ssl  22:11   0:15 transmission-daemon -g /home/goodmind/.config/transmission
avahi     4327  0.0  0.1  25916  2788 ?        Ss   22:13   0:00 avahi-daemon: running [goodmind-pc.local]
avahi     4328  0.0  0.0  25788   212 ?        S    22:13   0:00  \_ avahi-daemon: chroot helper
goodmind 17533  2.4  1.4 1080800 30204 ?       Ssl  22:20   1:30 mpd
lightdm   5094  0.0  0.2  35860  4364 ?        Ss   22:30   0:00 /usr/lib/systemd/systemd --user
lightdm   5095  0.0  0.0 244140  1304 ?        S    22:30   0:00  \_ (sd-pam)
lightdm   5108  0.0  0.0  18052  1872 ?        S    22:30   0:00 dbus-launch --autolaunch=640c040e7d23438197a2f427de343efd --binary-syntax --close-stderr
lightdm   5109  0.0  0.1  34516  2140 ?        Ss   22:30   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
goodmind  5128  0.0  0.0  18052  1972 ?        S    22:30   0:00 dbus-launch --sh-syntax --exit-with-session
goodmind  5129  0.0  0.1  34900  2692 ?        Ss   22:30   0:00 /usr/bin/dbus-daemon --fork --print-pid 5 --print-address 7 --session
goodmind  5137  0.0  0.6 267804 13780 ?        Sl   22:30   0:00 lxpolkit
goodmind  5139  0.0  0.2  53540  4668 ?        S    22:30   0:00 redshift
goodmind  5143  0.6  0.3  82460  6496 ?        S    22:30   0:18 compton
goodmind  5153  0.0  0.7 275452 14416 ?        Ssl  22:30   0:00 xfce4-power-manager
goodmind  5156  0.0  0.2  35280  4256 ?        S    22:30   0:00 /usr/lib/xfce4/xfconf/xfconfd
goodmind  5159  0.0  0.4 430248  8876 ?        Sl   22:30   0:00 /usr/bin/dunst
goodmind  5171  0.0  1.4 673220 29828 ?        Sl   22:30   0:01 haguichi --hidden
goodmind  5172  0.0  1.0 377364 21492 ?        Sl   22:30   0:00 light-locker
goodmind  5173  0.0  1.2 334868 25604 ?        Sl   22:30   0:00 pamac-tray
goodmind  5177  0.0  0.2 176216  4444 ?        Sl   22:30   0:00 /usr/lib/dconf/dconf-service
goodmind  5181  0.0  0.2 261720  5528 ?        Sl   22:30   0:00 /usr/lib/at-spi2-core/at-spi-bus-launcher
goodmind  5184  0.0  0.1  34516  3356 ?        S    22:30   0:00  \_ /usr/bin/dbus-daemon --config-file=/etc/at-spi2/accessibility.conf --nofork --print-address 3
goodmind  5187  0.0  0.3 123212  6172 ?        Sl   22:30   0:00 /usr/lib/at-spi2-core/at-spi2-registryd --use-gnome-session
goodmind  5191  0.0  0.3 221688  6844 ?        Sl   22:30   0:00 /usr/lib/gvfs/gvfsd
goodmind  5194  2.2  8.1 2816144 166416 ?      Sl   22:30   1:09 dropbox
goodmind  5195  0.1  4.9 1109316 101572 ?      Sl   22:30   0:03 /usr/bin/perl /usr/bin/shutter --min_at_startup
goodmind  5202  0.0  0.4 366488  8632 ?        Sl   22:30   0:00 /usr/lib/gvfs/gvfsd-fuse /run/user/1000/gvfs -f -o big_writes
goodmind  5232  1.8  0.7 622312 15032 ?        S<l  22:30   0:58 /usr/bin/pulseaudio --start --log-target=syslog
goodmind  5403  0.1  1.6 717600 34584 ?        Sl   22:30   0:03 thunar
goodmind  5407  0.0  0.5 311676 10440 ?        Sl   22:30   0:00 /usr/lib/gvfs/gvfs-udisks2-volume-monitor
goodmind  5412  0.0  0.2 191744  5584 ?        Sl   22:30   0:00 /usr/lib/gvfs/gvfs-mtp-volume-monitor
goodmind  5417  0.0  0.3 377984  7144 ?        Sl   22:30   0:00 /usr/lib/gvfs/gvfsd-trash --spawner :1.12 /org/gtk/gvfs/exec_spaw/0
goodmind  5475  0.0  0.2  45984  4972 ?        S    22:30   0:00 /usr/lib/GConf/gconfd-2
goodmind  7912  8.8 21.6 1690128 444604 ?      Sl   22:31   4:28 firefox
goodmind 11397  0.0  0.3 144624  6540 ?        Sl   22:33   0:00 /usr/lib/gvfs/gvfsd-metadata
goodmind 12520  0.2  1.4 620280 29420 ?        Sl   22:33   0:06 xfce4-terminal
goodmind 12558  0.0  0.0   8376  1596 ?        S    22:33   0:00  \_ gnome-pty-helper
goodmind 26718  0.0  0.2  38992  5500 pts/1    Ss+  22:41   0:00  \_ zsh
goodmind 21701  0.0  0.2  36612  5228 pts/0    Ss+  23:11   0:00  \_ zsh
goodmind 28190  0.0  0.2  38856  5532 pts/2    Ss+  23:14   0:00  \_ zsh
goodmind 32125  0.0  0.2  36804  5376 pts/3    Ss+  23:16   0:00  \_ zsh
goodmind 13019  0.0  0.8  57368 17804 ?        S    22:34   0:00 perl /usr/local/bin/i3-wsbar -c ~/.config/i3/bar/dzen2.sh --bar_id=status_bar --socket=/home/goodmind/.config/i3/i3-ipc.sock
goodmind 13021  0.0  0.4 129132  9544 ?        S    22:34   0:00 i3bar --bar_id=navigation_bar --socket=/home/goodmind/.config/i3/i3-ipc.sock
goodmind 13022  0.3  0.9 233324 18828 ?        Sl   22:34   0:10  \_ /usr/bin/python /usr/bin/py3status -c /home/goodmind/.config/i3status/config2
goodmind 13101  0.1  0.1  26736  2712 ?        S    22:34   0:02      \_ i3status -c /tmp/py3status_qw3c6pr5
goodmind 13093  0.0  0.1  15908  2644 ?        S    22:34   0:02 /bin/bash /home/goodmind/.config/i3/bar/dzen2.sh
goodmind 11678  0.0  0.0   7992   680 ?        S    23:22   0:00  \_ sleep 1
goodmind 13094  0.1  0.3  60976  6224 ?        S    22:34   0:04 dzen2 -p -title-name status_bar -dock -h 24 -fn -*-terminus-medium-r-*-*-12-*-*-*-*-*-iso10646-* -ta right -bg #3c3c3c -fg #A0A0A0
goodmind 26568  5.7  5.9 2218360 121716 ?      Sl   22:40   2:21 /opt/telegram/Telegram --
```

**Comment by Goodmind** [comment]
I have again 100% CPU by htop, but ```ps aufxww``` says there is only 13.7%

**Comment by stapelberg** [comment]
From your ps output:

```text
goodmind  5121  2.8  1.5 171340 32400 ?        Rs   22:30   1:30      \_ i3-with-shmlog -a --restart /run/user/1000/i3/restart-state.5121
root       296  0.0  0.2  89848  4272 ?        Ss   20:15   0:00 login -- goodmind
goodmind 17214  0.0  0.2  38924  5592 tty1     Ss   22:20   0:01  \_ -zsh
goodmind 11682  0.0  0.1  38784  3524 tty1     R+   23:22   0:00      \_ ps aufxww
```

The current local time is 23:22, because the `ps` command was just started. This means i3 has been running for 52 minutes. During these 52 minutes, it has been using an accumulated 1 minute and 30 seconds of CPU time.

So, on average, i3 has been using 2.8% of your CPU.

I don’t think there is a bug in i3 here, and what you are seeing must be caused by something else.

**Comment by Goodmind** [comment]
``` goodmind  20   0  166,7m  29,9m  93,8  1,5   1:50.23 R          `- i3-with-shmlog      ```

Why ```top``` saying there is 93,8% of CPU?

**Comment by stapelberg** [comment]
That top output has different columns from what top spits out on my system, so I can’t say why it shows a high number.

**Comment by Goodmind** [comment]
But i3 still in freeze and I can't do anything besides kill and relogin

**Comment by stapelberg** [comment]
You never mentioned that i3 is frozen for you, only that it’s using a lot of CPU. This should have been in your very first comment.

Can you please ensure your version of i3 was compiled with debug symbols and provide a full backtrace when attaching gdb to a frozen i3 process using `gdb $(which i3) $(pidof i3)` (see also step 4 and step 5 of http://i3wm.org/docs/debugging-release-version.html)?

**Comment by Goodmind** [comment]
Oh, thank you, I'll reproduce freeze and do it

**Comment by Goodmind** [comment]
Says that there is ```No stack.```

**Comment by Goodmind** [comment]
Oh, I need to recompile i3 with debug symbols?

**Comment by Goodmind** [comment]
gdb says that there is no debug symbols, but ```file $(which i3)``` says that it is not stripped

**Comment by Goodmind** [comment]
Oh, I need run gdb as root

**Comment by Airblader** [comment]
Please don't spam Github like this as every post triggers email notifications. You can just edit your comment to let us know that you noticed that you forgot something.

**Comment by Goodmind** [comment]
```
#0  0x00007f85156bcf30 in __write_nocancel () from /usr/lib/libpthread.so.0
No symbol table info available.
#1  0x00000000004374fa in writeall (fd=fd@entry=11, buf=buf@entry=0x9534d0, count=count@entry=7816) at libi3/safewrappers.c:74
        written = 0
        n = <optimized out>
#2  0x0000000000439283 in ipc_send_message (sockfd=11, message_size=7816, message_type=message_type@entry=2147483648, 
    payload=payload@entry=0x9534d0 "{\"change\":\"focus\",\"current\":{\"id\":9305760,\"type\":\"workspace\",\"orientation\":\"horizontal\",\"scratchpad_state\":\"none\",\"percent\":0.5,\"urgent\":false,\"focused\":false,\"layout\":\"splith\",\"workspace_layout\":\"tab"...) at libi3/ipc_send_message.c:38
        header = {magic = "i3-ipc", size = 7816, type = 2147483648}
#3  0x0000000000420b58 in ipc_send_event (event=event@entry=0x44322b "workspace", message_type=message_type@entry=2147483648, 
    payload=0x9534d0 "{\"change\":\"focus\",\"current\":{\"id\":9305760,\"type\":\"workspace\",\"orientation\":\"horizontal\",\"scratchpad_state\":\"none\",\"percent\":0.5,\"urgent\":false,\"focused\":false,\"layout\":\"splith\",\"workspace_layout\":\"tab"...) at ../i3/src/ipc.c:59
        current = 0x9252e0
#4  0x0000000000421dd3 in ipc_send_workspace_event (change=change@entry=0x4433a6 "focus", current=current@entry=0x8dfea0, old=old@entry=0x8e0580)
    at ../i3/src/ipc.c:1170
        gen = 0x95cfb0
        payload = 0x9534d0 "{\"change\":\"focus\",\"current\":{\"id\":9305760,\"type\":\"workspace\",\"orientation\":\"horizontal\",\"scratchpad_state\":\"none\",\"percent\":0.5,\"urgent\":false,\"focused\":false,\"layout\":\"splith\",\"workspace_layout\":\"tab"...
        length = 7816
#5  0x0000000000428098 in _workspace_show (workspace=0x8dfea0) at ../i3/src/workspace.c:414
        current = 0x8e0580
        old = <optimized out>
        new_output = <optimized out>
        next = 0x8e01e0
        old_output = 0x8df900
        workspace = 0x8dfea0
#6  0x0000000000413816 in cmd_workspace_name (current_match=<optimized out>, cmd_output=0x65a690 <subcommand_output>, name=0x8c5cc0 "1:web")
    at ../i3/src/commands.c:1062
        __FUNCTION__ = "cmd_workspace_name"
#7  0x00000000004240cb in GENERATED_call (result=0x65a690 <subcommand_output>, call_identifier=<optimized out>) at include/GENERATED_command_call.h:390
No locals.
#8  next_state (token=0x656bd0 <tokens_WORKSPACE+144>, token=0x656bd0 <tokens_WORKSPACE+144>) at ../i3/src/commands_parser.c:191
No locals.
#9  0x0000000000424ae6 in parse_command (input=input@entry=0x935180 "workspace \"1:web\"", gen=gen@entry=0x95cd60) at ../i3/src/commands_parser.c:329
        str = <optimized out>
        ptr = 0x443a90 <tokens+528>
        __FUNCTION__ = "parse_command"
        result = 0x8c6450
        walk = 0x935191 ""
        len = 17
        c = <optimized out>
        token = 0x656bd0 <tokens_WORKSPACE+144>
        token_handled = false
#10 0x000000000041fdc3 in handle_command (fd=10, message=0x930be0 "workspace \"1:web\"", size=<optimized out>, message_size=<optimized out>, 
    message_type=<optimized out>) at ../i3/src/ipc.c:92
        command = 0x935180 "workspace \"1:web\""
        gen = 0x95cd60
        result = <optimized out>
        reply = 0x88f00794b52da100 <error: Cannot access memory at address 0x88f00794b52da100>
        length = 0
#11 0x000000000041fe9a in ipc_receive_message (loop=0x7f8515f52a80, w=0x930a40, revents=<optimized out>) at ../i3/src/ipc.c:1033
        h = <optimized out>
        message_type = 0
        message_length = 17
        ret = <optimized out>
        __FUNCTION__ = "ipc_receive_message"
#12 0x00007f8515d485d3 in ev_invoke_pending () from /usr/lib/libev.so.4
No symbol table info available.
#13 0x00007f8515d4bc0e in ev_run () from /usr/lib/libev.so.4
No symbol table info available.
#14 0x0000000000409628 in ev_loop (flags=0, loop=<optimized out>) at /usr/include/ev.h:828
No locals.
#15 main (argc=<optimized out>, argv=<optimized out>) at ../i3/src/main.c:818
        override_configpath = <optimized out>
        autostart = false
        layout_path = <optimized out>
        delete_layout_path = <optimized out>
        force_xinerama = false
        fake_outputs = 0x0
        disable_signalhandler = false
        only_check_config = <optimized out>
        long_options = {{name = 0x4417c1 "no-autostart", has_arg = 0, flag = 0x0, val = 97}, {name = 0x446665 "config", has_arg = 1, flag = 0x0, val = 99}, {
            name = 0x4417df "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x4417ce "moreversion", has_arg = 0, flag = 0x0, val = 109}, {
            name = 0x4417da "more-version", has_arg = 0, flag = 0x0, val = 109}, {name = 0x4417e7 "more_version", has_arg = 0, flag = 0x0, val = 109}, {
            name = 0x4417f4 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x44338f "layout", has_arg = 1, flag = 0x0, val = 76}, {
            name = 0x443364 "restart", has_arg = 1, flag = 0x0, val = 0}, {name = 0x44686f "force-xinerama", has_arg = 0, flag = 0x0, val = 0}, {
            name = 0x44685f "force_xinerama", has_arg = 0, flag = 0x0, val = 0}, {name = 0x441303 "disable-signalhandler", has_arg = 0, flag = 0x0, val = 0}, {
            name = 0x441346 "shmlog-size", has_arg = 1, flag = 0x0, val = 0}, {name = 0x441352 "shmlog_size", has_arg = 1, flag = 0x0, val = 0}, {
            name = 0x441319 "get-socketpath", has_arg = 0, flag = 0x0, val = 0}, {name = 0x441328 "get_socketpath", has_arg = 0, flag = 0x0, val = 0}, {
            name = 0x44687f "fake_outputs", has_arg = 1, flag = 0x0, val = 0}, {name = 0x44688d "fake-outputs", has_arg = 1, flag = 0x0, val = 0}, {
            name = 0x441a80 "force-old-config-parser-v4.4-only", has_arg = 0, flag = 0x0, val = 0}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        option_index = 8
        opt = <optimized out>
        __FUNCTION__ = "main"
        _NET_SUPPORTED_cookie = <optimized out>
        _NET_SUPPORTING_WM_CHECK_cookie = <optimized out>
        _NET_WM_NAME_cookie = {sequence = 7}
        cookie = <optimized out>
        greply = <optimized out>
        extreply = <optimized out>
        needs_tree_init = <optimized out>
        pointerreply = <optimized out>
        output = <optimized out>
        ipc_socket = <optimized out>
        xcb_watcher = <optimized out>
        xcb_prepare = <optimized out>
        action = {__sigaction_handler = {sa_handler = 0x423770 <handle_signal>, sa_sigaction = 0x423770 <handle_signal>}, sa_mask = {__val = {
              0 <repeats 16 times>}}, sa_flags = -1073741820, sa_restorer = 0x1}
        exec_always = <optimized out>
        barconfig = 0x0
Detaching from program: /usr/bin/i3, process 25253
```

**Comment by stapelberg** [comment]
Thanks for the backtrace. My first guess is that the old and unsupported i3-wsbar has some bug and blocks your IPC connection. Try killing it when i3 freezes and the freeze should go away.

**Comment by Goodmind** [comment]
Thank you! It's works, but what replacement for i3-wsbar?

**Comment by stapelberg** [comment]
i3bar.

**Comment by Goodmind** [comment]
why i3-wsbar support is dropped? How to use custom bars with i3?

**Comment by stapelberg** [comment]
Because i3bar covers the use-case of i3-wsbar pretty well for a large number of users, and maintaining two entirely separate code-bases for workspace bars is not something we want to spend time on. Further, with i3-wsbar, you fundamentally cannot get a workspace tray, so that’s why we went with i3bar.

I’m not entirely sure how to answer the latter part of your question. Either you fix the bug in i3-wsbar that you are running into or you write your own thing. The interface which i3bar uses is documented at http://build.i3wm.org/docs/ipc.html
