### ISSUE TITLE
"-C" switch causes segfault

### ISSUE THREAD

**Issue by Airblader** [i3/i3#2144]
`i3 -C` causes a segfault because of 287a0b4c3cc24a18f5063b7d5743f0b85d6852a1

@Alexis211 FYI.

i3 4.11

**Comment by Airblader** [comment]
We really need to add a test for this command working, maybe by feeding it an invalid config and checking the output. We've broken this before.

**Comment by Airblader** [comment]
Relevant backtrace:

````
#0  0x0000000000451bf4 in get_colorpixel (hex=0x687670 "#b8bb26") at libi3/get_colorpixel.c:45
        strgroups = {"b8", "bb", "26"}
        r = 184 '\270'
        g = 187 '\273'
        b = 38 '&'
        colorpixel = 0x68cd90
        r16 = 6868336
        g16 = 0
        b16 = 6846064
        reply = 0x7fffffffc890
        pixel = 0
        cache_pixel = 0x7ffff7ffe488
#1  0x000000000044efa6 in draw_util_hex_to_color (color=0x687670 "#b8bb26") at libi3/draw_util.c:114
        alpha = "FF"
        groups = {"b8", "bb", "26", "FF"}
#2  0x00000000004212a4 in cfg_color (current_match=0x673ec0 <current_match>, result=0x673f40 <subcommand_output>, colorclass=0x687590 "client.focused", border=0x687670 "#b8bb26", background=0x68cd70 "#b8bb26", text=0x68cd90 "#212121", indicator=0x68cdb0 "#b8bb26") at ../i3-original/src/config_directives.c:352
No locals.
#3  0x0000000000446938 in GENERATED_call (call_identifier=51, result=0x673f40 <subcommand_output>) at include/GENERATED_config_call.h:414
        __PRETTY_FUNCTION__ = "GENERATED_call"
#4  0x00000000004471be in next_state (token=0x6708e0 <tokens_COLOR_INDICATOR>) at ../i3-original/src/config_parser.c:208
        _next_state = __CALL
#5  0x0000000000447837 in parse_config (input=0x688b00 "# vim:filetype=i3\n# i3 config file (v4)\nset Mod4 Mod4\nset termite termite\n\nset #212121       #212121\nset #000000   #000000\nset #fb4934         #fb4934\nset #cc241d     #cc241d\nset #b8bb26       #b8bb26"..., context=0x687470)
    at ../i3-original/src/config_parser.c:390
        str = 0x6875b0 ""
        inpos = 7
        outpos = 7
        beginning = 0x68902e "#b8bb26\nclient.unfocused        #212121      #212121      #ebdbb2 #212121\nclient.focused_inactive #212121      #212121      #ebdbb2 #212121\nclient.urgent", ' ' <repeats 11 times>, "#fb4934        #fb4934        #21212"...
        ptr = 0x672010 <tokens+752>
        dumpwalk = 0x68cadd ""
        linecnt = 58
        __FUNCTION__ = "parse_config"
        walk = 0x689035 "\nclient.unfocused        #212121      #212121      #ebdbb2 #212121\nclient.focused_inactive #212121      #212121      #ebdbb2 #212121\nclient.urgent", ' ' <repeats 11 times>, "#fb4934        #fb4934        #212121 #fb49"...
        len = 16349
        c = 0
        token = 0x6708e0 <tokens_COLOR_INDICATOR>
        token_handled = false
        __PRETTY_FUNCTION__ = "parse_config"
#6  0x00000000004490c6 in parse_file (f=0x684240 "/home/ingo/.i3/config", use_nagbar=false) at ../i3-original/src/config_parser.c:977
        variables = {slh_first = 0x6889f0}
        fd = 4
        stbuf = {st_dev = 2052, st_ino = 4850091, st_nlink = 1, st_mode = 33188, st_uid = 1000, st_gid = 100, __pad0 = 0, st_rdev = 0, st_size = 12762, st_blksize = 4096, st_blocks = 32, st_atim = {tv_sec = 1451705462, tv_nsec = 510243108}, st_mtim = {tv_sec = 1451705461, tv_nsec = 380206221}, st_ctim = {
            tv_sec = 1451705461, tv_nsec = 406873758}, __glibc_reserved = {0, 0, 0}}
        buf = 0x684280 "# vim:filetype=i3\n# i3 config file (v4)\nset $mod Mod4\nset $editor termite\n\nset $black       #212121\nset $darkblack   #000000\nset $red         #fb4934\nset $darkred     #cc241d\nset $green       #b8bb26\n"...
        fstr = 0x687470
        buffer = "exec_always --no-startup-id feh --bg-fill $HOME/.config/wallpapers/material.jpg\n\000n mouse\n\000\065\060 -set 90\n\000\000/span> <span foreground='#ebdbb2'>+</span> increase <span foreground='#ebdbb2'>-</span> decrease"...
        key = "exec_always\000\000ace\000e\000bers\000on\000th", '\000' <repeats 11 times>, "`\315\377\377\377\177\000\000\000\000\000\000\000\000\000\000\017\071\336\367\377\177\000\000\000\000\000\000\000\000\000\000\001\000\000\000\000\000\000\000\022\000\000\000\000\000\000\000p\\\373\367\377\177\000\000\060\341\377\367\377\177\000\000\000\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000\330\334\373\367\377\177\000\000\017\000\000\000\000\000\000\000p\\\373\367\377\177\000\000\000\351\377\377\377\177\000\000@\003\000\000\000\000\000\000\177ELF\002\001\001\000\000\000\000\000\000\000\000\000\003\000>\000\001\000\000\000\000)\000\000\000\000\000\000@\000\000\000\000\000\000\000"...
        value = "--no-startup-id feh --bg-fill $HOME/.config/wallpapers/material.jpg\000ion mouse\000\065\060 -set 90\000\000ghtness </span> <span foreground='#ebdbb2'>+</span> increase <span foreground='#ebdbb2'>-</span> decrease\000bb2"...
        continuation = 0x7fffffffced0 "exec_always --no-startup-id feh --bg-fill $HOME/.config/wallpapers/material.jpg\n"
        __FUNCTION__ = "parse_file"
        current = 0x0
        nearest = 0x0
        extra_bytes = 3587
        bufcopy = 0x0
        walk = 0x687372 "\n    }\n}\n\n# AUTOSTART\n\nexec --no-startup-id compton -b\nexec --no-startup-id dunst &\nexec --no-startup-id nm-applet &\nexec --no-startup-id xedgewarp -b\n\nexec_always --no-startup-id feh --bg-fill $HOME/"...
        destwalk = 0x68cadd ""
        new = 0x688b00 "# vim:filetype=i3\n# i3 config file (v4)\nset Mod4 Mod4\nset termite termite\n\nset #212121       #212121\nset #000000   #000000\nset #fb4934         #fb4934\nset #cc241d     #cc241d\nset #b8bb26       #b8bb26"...
        version = 4
        config_output = 0x7fffffffdf30
        has_errors = false
#7  0x000000000040e45e in parse_configuration (override_configpath=0x0, use_nagbar=false) at ../i3-original/src/config.c:65
        path = 0x684240 "/home/ingo/.i3/config"
#8  0x000000000041c3c2 in main (argc=2, argv=0x7fffffffe908) at ../i3-original/src/main.c:367
        _i3_version = 0x45cd88 "4.11-166-g287a0b4 (2015-12-29, branch \"bisect/good-c6a4e4519fb000fe835486bcb02f3253e4316a3b-1-g287a0b4\")"
        override_configpath = 0x0
        autostart = true
        layout_path = 0x0
        delete_layout_path = false
        force_xinerama = false
        fake_outputs = 0x0
        disable_signalhandler = false
        only_check_config = true
        long_options = {{name = 0x45a140 "no-autostart", has_arg = 0, flag = 0x0, val = 97}, {name = 0x45a14d "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x45a154 "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x45a15c "moreversion", has_arg = 0, flag = 0x0, val = 109}, {
            name = 0x45a168 "more-version", has_arg = 0, flag = 0x0, val = 109}, {name = 0x45a175 "more_version", has_arg = 0, flag = 0x0, val = 109}, {name = 0x45a182 "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x45a187 "layout", has_arg = 1, flag = 0x0, val = 76}, {name = 0x45856b "restart", 
            has_arg = 1, flag = 0x0, val = 0}, {name = 0x4583ac "force-xinerama", has_arg = 0, flag = 0x0, val = 0}, {name = 0x4583bb "force_xinerama", has_arg = 0, flag = 0x0, val = 0}, {name = 0x4584e7 "disable-signalhandler", has_arg = 0, flag = 0x0, val = 0}, {name = 0x45852a "shmlog-size", has_arg = 1, 
            flag = 0x0, val = 0}, {name = 0x458536 "shmlog_size", has_arg = 1, flag = 0x0, val = 0}, {name = 0x4584fd "get-socketpath", has_arg = 0, flag = 0x0, val = 0}, {name = 0x45850c "get_socketpath", has_arg = 0, flag = 0x0, val = 0}, {name = 0x458580 "fake_outputs", has_arg = 1, flag = 0x0, val = 0}, {
            name = 0x458573 "fake-outputs", has_arg = 1, flag = 0x0, val = 0}, {name = 0x4585b0 "force-old-config-parser-v4.4-only", has_arg = 0, flag = 0x0, val = 0}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}
        option_index = 0
        opt = -1
        __FUNCTION__ = "main"
        _NET_SUPPORTED_cookie = {sequence = 1}
        _NET_SUPPORTING_WM_CHECK_cookie = {sequence = 80}
        _NET_WM_NAME_cookie = {sequence = 96}
        _NET_WM_VISIBLE_NAME_cookie = {sequence = 6810304}
        _NET_WM_MOVERESIZE_cookie = {sequence = 4103073536}
        _NET_WM_STATE_STICKY_cookie = {sequence = 0}

```
