### ISSUE TITLE
Restarting i3 in-place twice segfaults the i3 process.

### ISSUE THREAD

**Issue by phijaro** [i3/i3#2414]
Output of `i3 --moreversion 2>&- || i3 --version`:

Binary i3 version:  4.12 (2016-03-06, branch "4.12") © 2009 Michael Stapelberg and contributors
Running i3 version: 4.12 (2016-03-06, branch "4.12") (pid 10360)
Loaded i3 config: /home/pjr/.i3/config (Last modified: Sat 30 Jul 2016 12:57:41 BST, 119555 seconds ago)

The i3 binary you just called: /usr/bin/i3
The i3 binary you are running: i3

URL to a logfile as per http://i3wm.org/docs/debugging.html:

http://logs.i3wm.org/logs/5691420614590464.bz2

(This log probably won't be very useful, as it's from the i3 session I started after the crash in order to file this report...)

**What I did:**

Hit $mod+Shift-R twice.  It doesn't seem to matter how much time elapses in between.

**What I saw:**

i3 crashed and dumped me back to the login screen; I also found the following line in my syslog:

`i3[9844]: segfault at 0 ip 000055be987cef96 sp 00007ffe74a3ed50 error 6 in i3[55be987ac000+68000]`

No dialog appeared offering the option to save a backtrace.

**What I expected instead:**

i3 to restart in-place.

**Comment by stapelberg** [comment]
Can you please verify whether this issue still persists on the latest `next` branch of i3?

Also, is there any way you can get a backtrace? Without it, debugging this crash will likely not be possible.

**Comment by phijaro** [comment]
OK, I've just found the instructions for attaching gdb in #2269; I'll try that out, and I'll give the latest `next` branch a go too.

**Comment by phijaro** [comment]
I've managed to get a backtrace using version 4.12-78-g85bb324, and I've also found some useful logs under /var/run.  The problem seems to be caused by a broader issue with placeholder windows: restarting i3 when multiple monitors are active scrambles them, such that some of them have empty swallow criteria, which, of course, i3 chokes on when trying to restore the session state when I restart a second time.  This is confirmed by the fact that when I close all open placeholder windows restarting any number of times works fine.

Mostly I'm drawing this conclusion from an errorlog file that reads as follows:

```
ERROR: Layout file is invalid: found an empty swallow definition.
ERROR: JSON parsing error: parse error: client cancelled parse via callback return value
          ing":"auto_off","swallows":[{},{"instance":"^thunar$"}]},{"i
                     (right here) ------^
```

Other files that are potentially relevant for further investigation: [gdb_session.txt](https://github.com/i3/i3/files/392686/gdb_session.txt) [restart-state.5479.txt](https://github.com/i3/i3/files/392688/restart-state.5479.txt)

I'll open another issue to describe the odd behaviour of placeholders in detail, with a hopefully more relevant shmlog and a few screenshots.

If I'm right, then I guess the pith of this issue now is this: maybe i3 should deal more gracefully with corrupted restart-states, so that users don't lose data unexpectedly?  I know I'd rather it just skipped rendering a placeholder window as opposed to dropping all my running programs on the floor.  Unfortunately I don't have the C chops to generate a patch (I'm just a lowly Python hacker!)

**Comment by Airblader** [comment]
I haven't tried to reproduce this yet, but assuming you're right:

> maybe i3 should deal more gracefully with corrupted restart-states

IMHO, yes and no. Of course we should _never_ crash. On the other hand, a corrupted restart state is a should-never-ever-happen kind of thing without user interaction. So the proper fix for me is to avoid running into this scenario altogether. For that, of course, we need to figure out what exactly is going wrong.

**Comment by Airblader** [comment]
@phijaro I'm actually not entirely sure what separates the second issue, #2415, from this one. Can you elaborate? I think this is really just one underlying issue and unless I'm missing something, I'd close this in favor of the other one (since the other one has a lot of useful information).

**Comment by phijaro** [comment]
I share your "yes and no" assessment completely.  I think #2415 should definitely be addressed as a higher priority than hardening the code against restart-state corruption, but if somebody did have the Copious Free Time to do it, we'd be protected in the event that some other cause of corrupted restart states crops up.  So I think this issue should stay live and distinct from #2415, but low-priority.  Maybe even "waiting until @phijaro learns enough C to patch it" low-priority...

**Comment by Airblader** [comment]
We'd still have to weigh the benefit of this robustness against the maintenace effort. Ultimately, it's impossible to protect against all kinds of corruption. If the JSON is syntactically invalid, it will be impossible to parse it anythin in it. Unless we have a robust JSON parser (much like modern HTML engines), which I think is orders of magnitude too much complexity to be worth it.

Given the benefit-cost calculation comes back positive, we can of course always accept changes increasing robustness. But I think issues should only exist for things that can be finished at some point and this would be something that can never be "finished", meaning this issue would float around forever. So I still favor closing the "robustness" issue and focusing on fixing the actual bug here.

@stapelberg What do you think?

**Comment by phijaro** [comment]
I can see how trying to recover from mangled JSON would be a lot of effort for hardening against a pretty remote chance of failure.  What about giving up on restoring the layout, but preserving the user's session (i.e. giving windows to running processes that need them in some sort of default layout — tabbed or stacked on a single workspace, maybe)?

**Comment by Airblader** [comment]
Yes, not crashing but simply forgetting the layout to restore sounds like a good plan to me.

**Comment by stapelberg** [comment]
> Yes, not crashing but simply forgetting the layout to restore sounds like a good plan to me.

Agreed. Handling invalid input gracefully is generally a good thing (not crash) and we should chose the most pragmatic way (forgetting the layout), aside — obviously — from fixing the underlying bug here :).

**Comment by chrysn** [comment]
I'm experiencing the same crash (a `"swallows":[{},...]` in the get_tree output) when using edited `i3-save-tree` output; a reduced example is [attached](https://github.com/i3/i3/files/1503785/minimal-crashing.txt); loading it into a fresh session using `append_layout` and reloading triggers the crash.

Does that work on your boxes as well, or can I provide any more debugging output?

**Comment by orestisf1993** [comment]
>  and reloading i3 triggers the crash

`restart`ing

The problems start when the first placeholder window swallows the second:
```
{
    "layout": "split",
    "type": "con",
    "nodes": [
	{
	    "swallows": [
	       {
		"title": "^XXX$"
	       }
	    ],
	    "type": "con"
	},
	{
	    "name": "XXX",
	    "swallows": [
	       {
		"class": "whatever"
	       }
	    ],
	    "type": "con"
	}
    ]
}
```

**Comment by orestisf1993** [comment]
Another example of this bug (no crash):

- Open urxvt
- `i3-msg append_layout layout.txt`
- move urxvt to the right (placeholder window first in node stack)
- restart

layout.txt:
```
{
    "swallows": [
       {
	"class": "URxvt"
       }
    ],
    "type": "con"
}
```

What happens: the temporary placeholder opened in https://github.com/i3/i3/blob/9dc4df81ea8e9739f570eb5191e62d2c27e31106/src/restore_layout.c#L228-L233 is not used since `con_for_window` in https://github.com/i3/i3/blob/9dc4df81ea8e9739f570eb5191e62d2c27e31106/src/manage.c#L256 matches the window using the previously opened placeholder.

**Comment by jendrikw** [comment]
I think I ran into this issue, but I'm not sure, as I cannot reproduce. Im on archlinux with version

```
Binary i3 version:  4.25.1 © 2009 Michael Stapelberg and contributors
Running i3 version: 4.25.1 (pid 160750)
```

These lines from my config may be relevant:

```
exec_always --no-startup-id autorandr --change
exec_always --no-startup-id killall polybar; xrandr --listactivemonitors | grep -oP '(HDMI\-\d+$|eDP\-\d+$)' | xargs -P1 -I{} bash -c "MONITOR={} polybar -q -r &"
```

autorandr also runs via udev if any screen is plugged or unplugged.

Anyways, here is the coredump, I hope it's useful: 

[i3.coredump.zip](https://github.com/user-attachments/files/26223892/i3.coredump.zip)

This is the restart state: 

[i3-restart-state.813.json](https://github.com/user-attachments/files/26223990/i3-restart-state.813.json)

And this is a snipped from the coredump

```
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563b8d42254b in con_focus (con=0x563bccce5740) at ../src/con.c:256
256	    TAILQ_REMOVE(&(con->parent->focus_head), con, focused);
   0x0000563b8d42252d <con_focus+61>:	48 8b 83 90 01 00 00	mov    rax,QWORD PTR [rbx+0x190]
   0x0000563b8d422534 <con_focus+68>:	48 8b 93 98 01 00 00	mov    rdx,QWORD PTR [rbx+0x198]
   0x0000563b8d42253b <con_focus+75>:	48 85 c0           	test   rax,rax
   0x0000563b8d42253e <con_focus+78>:	0f 84 8c 00 00 00  	je     0x563b8d4225d0 <con_focus+224>
   0x0000563b8d422544 <con_focus+84>:	48 89 90 98 01 00 00	mov    QWORD PTR [rax+0x198],rdx
=> 0x0000563b8d42254b <con_focus+91>:	48 89 02           	mov    QWORD PTR [rdx],rax
[Current thread is 1 (Thread 0x7f51b63548c0 (LWP 813))]
(gdb) t apply all bt

Thread 2 (Thread 0x7f51b43ff6c0 (LWP 160178)):
#0  syscall () at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
#1  0x00007f51b6e34a2e in g_cond_wait_impl (cond=0x563bccbe59e8, mutex=0x563bccbe59e0) at ../glib/glib/gthread-posix.c:1026
#2  g_cond_wait (cond=0x563bccbe59e8, mutex=0x563bccbe59e0) at ../glib/glib/gthread.c:1686
#3  0x00007f51b6dce22d in g_async_queue_pop_intern_unlocked (queue=0x563bccbe59e0, wait=1, end_time=-1) at ../glib/glib/gasyncqueue.c:376
#4  0x00007f51b6dce29d in g_async_queue_pop (queue=queue@entry=0x563bccbe59e0) at ../glib/glib/gasyncqueue.c:410
#5  0x00007f51b67d451c in fc_thread_func (data=0x563bccbe59e0) at ../pango/pango/pangofc-fontmap.c:997
#6  0x00007f51b6e3e13c in g_thread_proxy (data=0x563bccbe5a30) at ../glib/glib/gthread.c:893
#7  0x00007f51b6c3c97a in start_thread (arg=<optimized out>) at pthread_create.c:454
#8  0x00007f51b6cc02bc in __GI___clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:78

Thread 1 (Thread 0x7f51b63548c0 (LWP 813)):
#0  0x0000563b8d42254b in con_focus (con=0x563bccce5740) at ../src/con.c:256
#1  0x0000563b8d422594 in con_focus (con=0x563bccce5920) at ../src/con.c:259
#2  0x0000563b8d43ce80 in con_activate (con=0x563bccce5920) at ../src/con.c:293
#3  tree_append_json (con=0x563bccbe6a50, buf=<optimized out>, len=<optimized out>, errormsg=0x0) at ../src/load_layout.c:764
#4  0x0000563b8d448853 in tree_restore (path=<optimized out>, geometry=0x563bccbd2ae0) at ../src/tree.c:91
#5  0x0000563b8d406110 in main (argc=<optimized out>, argv=<optimized out>) at ../src/main.c:926
```
